### PR TITLE
Add appveyor build for Node 5.0 (ABI 47)

### LINKED ISSUE #102: Precompiled Binaries for newer node versions
There should be precompiled binaries for Windows on node 4.2.* since its a LTS. Precompiled v5 would be nice too.

### PR DESCRIPTION
**Pull request by kevinmehall**
Closes #102

### CODE REVIEW

**Comment by EvanSimpson** [comment]
@tcr :+1: for Node 5 support.

**Comment by kevinmehall** [comment]
Oh, I was just waiting for the CI builds to complete...

**Comment by EvanSimpson** [comment]
Awesome, thanks for getting it in!

**Comment by tcr3dr** [comment]
@kevinmehall pahahahahaha

**Comment by tcr3dr** [comment]
@EvanSimpson nice to see you here

**Pull request merged**
