### PR TITLE
[WIP] Upgrade to Nan 2.x

### PR DESCRIPTION
**Pull request by LinusU**
Work in progress, don't merge yet.

### CODE REVIEW

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by LinusU** [comment]
I'm having problem with the conversion of `_NanWeakCallbackInfo<Value, libusb_device>*>`, I don't see why it would take two types...

**Comment by kevinmehall** [comment]
See https://github.com/nodejs/nan/blob/master/doc/persistent.md#nanweakcallbackinfo

I think it would be replaced with a `Persistent<v8::Object>` in the `byPtr` map and a `WeakCallbackInfo<libusb_device>` in the callback function signature. You would put the `Persistent` in the map after you call `SetWeak` on it.

**Comment by LinusU** [comment]
I think that there was a problem with that but I don't remember what at the moment...

**Comment by paullryan** [comment]
Any progress or things I can help with? I'm working a project that needs this upgrade, I'm trying in parallel to your effort but am stumbling in similar places.

**Comment by paullryan** [comment]
My version is at https://github.com/SimplyComplexCo/node-usb/tree/nan2, the only errors left are the ones in the callback.

**Comment by paullryan** [comment]
@kevinmehall or @LinusU  have you gotten a persistent working in a map yet?

With the following definition:
```c++
// Map pinning each libusb_device to a particular V8 instance
std::map<libusb_device*, Persistent<Object>*> Device::byPtr;

void DeviceWeakCallback (const Nan::WeakCallbackInfo<libusb_device*> &data) {
	Device::unpin(*data.GetParameter());
}

// Get a V8 instance for a libusb_device: either the existing one from the map,
// or create a new one and add it to the map.
Local<Value> Device::get(libusb_device* dev){
	auto it = byPtr.find(dev);
	if (it != byPtr.end()){
		//return it->second;
	} else {
		Isolate* isolate = Isolate::GetCurrent();
		Local<Object> obj = Nan::New<Object>();
 		v8::Persistent<Object> v(isolate, obj);
		v.SetWeak(&dev, DeviceWeakCallback, WeakCallbackType::kParameter);
		byPtr.insert(std::make_pair(dev, &v));
		return obj;
	}
}
```

I'm getting the this error
``` shell
../src/device.cc:48:5: error: no matching member function for call to 'SetWeak'
                v.SetWeak(&dev, DeviceWeakCallback, WeakCallbackType::kParameter);
                ~~^~~~~~~
/Users/pryan/.node-gyp/4.0.0/include/node/v8.h:574:18: note: candidate function [with P = libusb_device *] not viable: no known conversion from 'void (const Nan::WeakCallbackInfo<libusb_device *> &)' to 'typename WeakCallbackInfo<libusb_device *>::Callback'
      (aka 'void (*)(const WeakCallbackInfo<libusb_device *> &)') for 2nd argument
  V8_INLINE void SetWeak(P* parameter,
                 ^
/Users/pryan/.node-gyp/4.0.0/include/node/v8.h:550:12: note: candidate function template not viable: requires 2 arguments, but 3 were provided
      void SetWeak(P* parameter,
           ^
/Users/pryan/.node-gyp/4.0.0/include/node/v8config.h:347:48: note: expanded from macro 'V8_DEPRECATE_SOON'
#define V8_DEPRECATE_SOON(message, declarator) declarator
                                               ^
/Users/pryan/.node-gyp/4.0.0/include/node/v8.h:556:12: note: candidate function template not viable: requires 2 arguments, but 3 were provided
      void SetWeak(P* parameter,
           ^
/Users/pryan/.node-gyp/4.0.0/include/node/v8config.h:347:48: note: expanded from macro 'V8_DEPRECATE_SOON'
#define V8_DEPRECATE_SOON(message, declarator) declarator
```

Astute readers will also notice I've commented out the other portion of the if until I figure out the best way to make that Peristent<Object> into a Local<Object> but that kind of handle conversion is no longer automatic in the new v8. 

Any thoughts on that are welcome as well.

**Comment by paullryan** [comment]
If you look at the current version of my code I'm just down to that pesky persistent return. Do I need to refactor the entire Get chain?

``` c++
// Map pinning each libusb_device to a particular V8 instance
std::map<libusb_device*, Persistent<Object>*> Device::byPtr;

void DeviceWeakCallback (const WeakCallbackInfo<libusb_device*> &data) {
	Device::unpin(*data.GetParameter());
}

// Get a V8 instance for a libusb_device: either the existing one from the map,
// or create a new one and add it to the map.
Local<Value> Device::get(libusb_device* dev){
	auto it = byPtr.find(dev);
	if (it != byPtr.end()){
		return it->second; // This is the only failure left in compiling...
	} else {
		Isolate* isolate = Isolate::GetCurrent();
		Local<Object> obj = Nan::New<Object>();
 		v8::Persistent<Object> v(isolate, obj);
		v.SetWeak(&dev, DeviceWeakCallback, Nan::WeakCallbackType::kParameter);
		byPtr.insert(std::make_pair(dev, &v));
		return obj;
	}
}
```

**Comment by paullryan** [comment]
Any thoughts @LinusU  or @kevinmehall I'm currently getting it to build but not run with this version I'm getting a init error on the usb_binding.node module.

**Comment by heavyk** [comment]
@LinusU  - #91 will resolve these issues (and I can guarantee it to be working with one device).

cheers

**Comment by kevinmehall** [comment]
Closing as #91 merged this.

**Pull request closed without merging**
