### PR TITLE
convert to nan-2

### PR DESCRIPTION
**Pull request by heavyk**
the second commit exposes `set_configuration` and allows for non-default configurations. I can remove it later if necessary. it's just, that without it, I cannot test. (my device emits `LIBUSB_ERROR_NOT_FOUND` with the default configuration)

thanks

ref: #90

### CODE REVIEW

**Comment by heavyk** [comment]
oh yes, I forgot to mention: I had to make a generic struct to hold the `Persistent<Object>` for the weak ref. so, because I do not have more than one device, I cannot verify that the weakref gcs correctly and the `std::map` is updated properly. so someone, with more than one device, can you do that test for me?

**Comment by kkoopa** [comment]
You may be interested in something like https://v8docs.nodesource.com/io.js-3.0/df/d6f/classv8_1_1_std_persistent_value_map.html or https://v8docs.nodesource.com/io.js-3.0/d3/d4c/classv8_1_1_persistent_value_map.html

**Comment by heavyk** [comment]
oh, that's great! thanks! I'll update this soon with a `PersistentValueMap`. seems straightforward enough

cheers :+1:

**Comment by kkoopa** [comment]
They might not be available on older versions than 0.12, but that can be fixed. Try it out and see.

**Comment by heavyk** [comment]
I take back what I said about it being straightforward. I totally don't get it. I don't understand this traits thing. I've searched on google for examples of how to use it and have found none.. zero. not one example anywhere.

so, reading the header, I see how its backed by `std::map` and calls `map.find()` in the `.Get()` function. I get that.

but, how do I instantiate it?

`PersistentValueMap<libusb_device*, v8::Object, ??????> Device::byPtr;`

**Comment by heavyk** [comment]
ok, almost got it, but there are two things:

1. I don't understand how to check if the `Local<Object>` is `kPersistentContainerNotFound`.
2. I don't know how to set the weak callback - but after looking at the source, I don't think I need to. it appears that it'll remove it from the map automatically [here](https://github.com/v8/v8/blob/92e85aed109d03498eb8cb5ad1b10e95b1686e42/include/v8-util.h#L382-L391) then [here](https://github.com/v8/v8/blob/92e85aed109d03498eb8cb5ad1b10e95b1686e42/include/v8-util.h#L382-L391), lastly [here](https://github.com/v8/v8/blob/92e85aed109d03498eb8cb5ad1b10e95b1686e42/include/v8-util.h#L404-L414) -- but, it won't print the debug info in `unpin` (not that big of a deal)

here's the diff:

```diff
diff --git a/src/device.cc b/src/device.cc
index f63312e..75407cf 100644
--- a/src/device.cc
+++ b/src/device.cc
@@ -28,7 +28,7 @@ Device::~Device(){
 }
 
 // Map pinning each libusb_device to a particular V8 instance
-std::map<libusb_device*, DeviceObject*> Device::byPtr;
+StdPersistentValueMap<libusb_device*, v8::Object> Device::byPtr(Isolate::GetCurrent());
 
 void DeviceWeakCallback(const Nan::WeakCallbackInfo<libusb_device> &data)  {
 	Device::unpin(data.GetParameter());
@@ -37,24 +37,22 @@ void DeviceWeakCallback(const Nan::WeakCallbackInfo<libusb_device> &data)  {
 // Get a V8 instance for a libusb_device: either the existing one from the map,
 // or create a new one and add it to the map.
 Local<Object> Device::get(libusb_device* dev){
-	auto it = byPtr.find(dev);
-	if (it != byPtr.end()){
-		return Nan::New(it->second->obj);
+	Local<Object> it = byPtr.Get(dev);
+	if (it != kPersistentContainerNotFound) {
+		return it;
 	} else {
 		Local<FunctionTemplate> constructorHandle = Nan::New<v8::FunctionTemplate>(device_constructor);
 		Local<Value> argv[1] = { EXTERNAL_NEW(new Device(dev)) };
 		Local<Object> obj = constructorHandle->GetFunction()->NewInstance(1, argv);
-		Nan::Persistent<Object> p(obj);
-		DeviceObject* dd = new DeviceObject;
-		dd->obj.Reset(p);
-		p.SetWeak(dev, DeviceWeakCallback, Nan::WeakCallbackType::kParameter);
-		byPtr.insert(std::make_pair(dev, dd));
+		// I don't understand how to set this DeviceWeakCallback to be called
+		// p.SetWeak(dev, DeviceWeakCallback, Nan::WeakCallbackType::kParameter);
+		byPtr.Set(dev, obj);
 		return obj;
 	}
 }
 
 void Device::unpin(libusb_device* device) {
-	byPtr.erase(device);
+	byPtr.Remove(device);
 	DEBUG_LOG("Removed cached device %p", device);
 }
 
diff --git a/src/node_usb.h b/src/node_usb.h
index f7bbfa8..32794cc 100644
--- a/src/node_usb.h
+++ b/src/node_usb.h
@@ -10,6 +10,7 @@
 #endif
 #include <libusb.h>
 #include <v8.h>
+#include <v8-util.h>
 
 #include <node.h>
 #include <node_buffer.h>
@@ -22,10 +23,6 @@ using namespace node;
 
 Local<Value> libusbException(int errorno);
 
-struct DeviceObject {
-	Nan::Persistent<Object> obj;
-};
-
 struct Device: public Nan::ObjectWrap {
 	libusb_device* device;
 	libusb_device_handle* device_handle;
@@ -42,9 +39,7 @@ struct Device: public Nan::ObjectWrap {
 	static void unpin(libusb_device* device);
 
 	protected:
-		// static std::map<libusb_device*, WeakCallbackInfo<libusb_device>*> byPtr;
-		// static std::map<libusb_device*, Persistent<Value>*> byPtr;
-		static std::map<libusb_device*, DeviceObject*> byPtr;
+		static StdPersistentValueMap<libusb_device*, v8::Object> byPtr;
 		Device(libusb_device* d);
 };
```

I think that'll work, but I don't know how to write that line there `if (it != kPersistentContainerNotFound) {`

**Comment by kkoopa** [comment]
`if (!it.IsEmpty()) { return it; } else {}`

**Comment by heavyk** [comment]
wow, that's it?! on hindsight I guess it seems obvious. whatever.

so, you da man! everything's working like it should...

----

I think my PR is ready now. unfortunately, I kept using this branch to develop on, so between then and now, a few commits have been added since (and I'm not entirely sure how to make commits in the middle disappear). I think they're essential additions, but if for some reason you do not want them, cherry pick the ones you want, or I can rebuild the branch and force push. again, apologies.

* e15da4f use `StdPersistentValueMap` from v8-util.h
* 88198b0 add error constants
* a59c120 try catch on transfer cancel
* 6f18d66 setConfiguration option
* 58eb19b convert to nan2

**Comment by kevinmehall** [comment]
Does the `StdPersistentValueMap` use weak persistent values, or is this leaking all the unused objects?

**Comment by kkoopa** [comment]
I assume it is currently using the default traits class https://v8docs.nodesource.com/io.js-3.0/d0/d08/classv8_1_1_default_persistent_value_map_traits.html and thus leaking. It should use a traits class with appropriate weak callback, but that might have different syntax for different versions..

**Comment by johnnyman727** [comment]
@heavyk what's going on with this PR? Anything I can do to help?

**Comment by heavyk** [comment]
it's done. all working and everything. (at least for me anyway)

@kevinmehall, if you look at the `StdPersistentValueMap ` source code you will see that should be removing itself from the map automatically [here](https://github.com/v8/v8/blob/92e85aed109d03498eb8cb5ad1b10e95b1686e42/include/v8-util.h#L382-L391) then [here](https://github.com/v8/v8/blob/92e85aed109d03498eb8cb5ad1b10e95b1686e42/include/v8-util.h#L382-L391), lastly [here](https://github.com/v8/v8/blob/92e85aed109d03498eb8cb5ad1b10e95b1686e42/include/v8-util.h#L404-L414)

are you seeing leaks? I've been using this code the last week without a problem. commit a59c120 was added (was another PR) because when I was testing the add remove while in middle of a transfer and was getting extra errors from the transfer.

**Comment by heavyk** [comment]
also, I see that node 0.10.x is failing. should I roll back the `StdPersistentValueMap` changes and just go back to a struct which holds a `Persistent<Object>`?

**Comment by johnnyman727** [comment]
@kevinmehall can you please take a look at this so we can get Node 4.x compat working for Tessel?

**Comment by heavyk** [comment]
to support node 0.10.x, I'm going to remove the final commit (the `StdPersistentValueMap` from v8-util.h one) because it works properly without it, and it does the same thing. will update later today.

**Comment by johnnyman727** [comment]
@heavyk it looks like your branch won't build on my machine:
```
➜  Code  git clone git@github.com:heavyk/node-usb.git
Cloning into 'node-usb'...
remote: Counting objects: 1450, done.
remote: Total 1450 (delta 0), reused 0 (delta 0), pack-reused 1450
Receiving objects: 100% (1450/1450), 497.26 KiB | 204.00 KiB/s, done.
Resolving deltas: 100% (875/875), done.
Checking connectivity... done.
➜  Code  cd node-usb
➜  node-usb git:(master) npm install
npm WARN installMany node-pre-gyp was bundled with usb@1.0.6, but bundled package wasn't found in unpacked tree
npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
-
> usb@1.0.6 install /Users/Jon/Code/node-usb
> node-pre-gyp install --fallback-to-build

make: *** No rule to make target `Release/obj.target/libusb/libusb/libusb/core.o', needed by `Release/usb.a'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Jon/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/Users/Jon/.nvm/versions/node/v4.1.2/bin/node" "/Users/Jon/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/Jon/Code/node-usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/Users/Jon/Code/node-usb/src/binding"
gyp ERR! cwd /Users/Jon/Code/node-usb
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/Jon/.nvm/versions/node/v4.1.2/bin/node /Users/Jon/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/Jon/Code/node-usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/Users/Jon/Code/node-usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Jon/Code/node-usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 13.4.0
node-pre-gyp ERR! command "/Users/Jon/.nvm/versions/node/v4.1.2/bin/node" "/Users/Jon/Code/node-usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Jon/Code/node-usb
node-pre-gyp ERR! node -v v4.1.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute '/Users/Jon/.nvm/versions/node/v4.1.2/bin/node /Users/Jon/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/Jon/Code/node-usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/Users/Jon/Code/node-usb/src/binding' (1)

npm ERR! Darwin 13.4.0
npm ERR! argv "/Users/Jon/.nvm/versions/node/v4.1.2/bin/node" "/Users/Jon/.nvm/versions/node/v4.1.2/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! usb@1.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb@1.0.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls usb
npm ERR! There is likely additional logging output above.
```

Do you have an idea what the issue is or if I tried to install it incorrectly (I don't have much experience with binary modules)?

**Comment by johnnyman727** [comment]
@heavyk btw, let me know if there is anything else I can do to help get this merged. I'll be super excited to get it merged into [`t2-cli`](github.com/tessel/t2-cli).

**Comment by kevinmehall** [comment]
@johnnyman727 are you missing the libusb submodule?

**Comment by heavyk** [comment]
you installed it incorrectly - or something. I had this issue too. it's something with node-pre-gyp. I remember that I had to run `node-gyp build` instead of `node-gyp rebuild`. I'll have a look at it tomorrow

**Comment by heavyk** [comment]
@kevinmehall that's correct. you cannot just put "usb": "heavyk/node-usb#nan-2" in the package.config. I'll add a check in the install script tommorow.

**Comment by johnnyman727** [comment]
Thanks @heavyk and @kevinmehall, I did miss the `--recursive` flag in the build instructions.

I am still running into another issue when I call `require('usb')` (with a try catch block):
```
[Error: Module version mismatch. Expected 14, got 46.]
```
What is actually generating that error?

**Comment by kevinmehall** [comment]
@johnnyman727 You're running an old version of Node and trying to load a module compiled for a newer version. Mixup with `nvm`?

**Comment by johnnyman727** [comment]
@kevinmehall yeah you just beat me to the post. I used `nvm` in one window to update to Node 4.2.1 and then tried using the `usb` module in another terminal window. Whoops!

In any case, the changes to get it working with Node 4.x.x are looking good from here! Tessel 2 is back up and running on Node 4. Thanks @heavyk!

**Comment by kevinmehall** [comment]
I read through the diff again and the only significant issue is the removal of the `Device::unpin` mechanism as I already noted. The `Device::byPtr` table *needs* to be using weak persistent references and remove entries from the map when the weak reference dies. Otherwise, the strong persistent references completely prevent the V8 GC from collecting any `Device` or object it references.

Yes, that will be slow leak in the majority of use cases because you don't typically add and remove devices very fast. But there's one application of this library [in the Tessel factory test](https://github.com/tessel/t2-test-rig-sw/tree/master/client) with a long-running process on a machine that sees thousands of attach cycles an hour, for instance. And it's simply incorrect memory management.

I'd also like to preserve Node 0.10 compatibility as this is the default version on Ubuntu 14.04 LTS.

**Comment by heavyk** [comment]
@kevinmehall I agree. I have updated. please test. going to bed now. I'll fix anything remaining tomorrow

**Comment by kevinmehall** [comment]
I found a better way to deal with the un-copyable `Persistent` and avoid need for the `DeviceObject` struct by constructing the `Persistent` in-place in the map:  a0fddb6f (BTW: the `DeviceObject` allocation was never freed -- that should have been a `unique_ptr` instead of a raw pointer if we were to go that route)

Tested against the Official node-usb Test Device on Node 0.10.25, 0.12.7, and 4.2.1 under Linux. Appveyor Windows builds are failing; looks unrelated, but will need to be fixed before we can test on Windows and release.

**Comment by kevinmehall** [comment]
Thanks @heavyk, @paullryan, and @LinusU for your work on this.

**Comment by heavyk** [comment]
NICE!! thanks

**Comment by johnnyman727** [comment]
:clap::clap:

**Comment by heavyk** [comment]
@kevinmehall - oh yes, I often forget to take out the garbage in c++. I've never actually studied c++. I just wing it copying other people's patterns. it's good to know about `unique_ptr`. that's a nice feature. thanks!

and yeah, the reason why I didn't put the persistent directly into the map without the `DeviceObject` is cause I couldn't figure the syntax, but I knew how to put a struct into a map :D haha... thanks

**Pull request merged**
